# Generated by Django 4.0.2 on 2022-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_last_edited', models.DateTimeField()),
            ],
            options={
                'db_table': 'mock_datas',
            },
        ),
    ]
